---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
framework_version: 3.3.1
serverless_language: node
polling_url: ''
polling_headers: ''
polling_body: ''
id: 464618
oauth_enabled: 'false'
oauth_pkce_enabled: 'no'
oauth_authorize_url: ''
oauth_token_url: ''
oauth_scopes: ''
oauth_scope_separator: ''
oauth_refresh_url: ''
oauth_auth_params: ''
oauth_token_headers: ''
oauth_token_site: ''
oauth_token_params: ''
oauth_token_request_auth_method: ''
oauth_body_format: ''
oauth_token_response_metadata: ''
oauth_authorization_method: ''
oauth_refresh_params: ''
oauth_token_field_name: ''
oauth_expiry_field_name: ''
oauth_expiry_strategy: ''
oauth_fixed_expiry_ms: ''
custom_fields:
- keyname: district_id
  field_type: string
  name: District ID
  description: Find your school using https://lookup.nutrislice.com/. Examine the URL in your browser. The district is the section before .nutrislice.com (i.e. mydistrict.nutrislice.com, write mydistrict here)
- keyname: school_id
  field_type: string
  name: School ID
  description: The last section of the URL, after /menu/ (i.e. https://mydistrict.nutrislice.com/menu/myschool, write myschool here
name: Chompy
description: ''
refresh_interval: 15
